### ISSUE TITLE
 http://localhost:3000  isn't working

### ISSUE THREAD

**Issue by Mannxxx** [shahriarshafin/disney-plus-clone#4]
Despite of running "npm start", the link isn't working. It gives the following error:
![image](https://github.com/shahriarshafin/disney-plus-clone/assets/107349957/5033fa5a-204b-46b1-abb5-82423be8b39a)

**Comment by shahriarshafin** [comment]
Thank you for reporting the issue. Run the following commands one by one it is working from my side

### 1. `npm install`
### 2. `npm audit fix`
### 3. `npm audit fix --force`
### 4. `npm start`
